---

name: release
run-name: release-${{ github.ref_name }}
on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  gap-branch: stable-4.14
  revision: ${{ github.event.repository.name }}-${{ github.ref_name }}
  archive-file:  ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz

jobs:
  assets-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: git -- checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'

      - name: gap -- release package
        uses: limakzi/gap-action-release-pkg@v1
        with:
          upload-artifacts: 'true'


  update-website:
    runs-on: ubuntu-22.04
    needs: assets-build
    permissions:
      contents: write
    steps:
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}

      - name: git -- checkout page
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - name: website -- download asset to be deployed
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: ${{ env.archive-file }}

      - name: website -- extract the archive
        run: |
          tar -xvf ${{ env.archive-file }}

      - name: metadata -- copy metada to update page
        run: |
          rm -r ./gh-pages/doc
          cp -r ${{ env.revision }}/doc/ ./gh-pages/doc/
          cp ${{ env.revision }}/PackageInfo.g ./gh-pages/PackageInfo.g
          cp ${{ env.revision }}/README.md ./gh-pages/README.md
          rm -v ./gh-pages/doc/.gitignore

      - name: gap -- run update.g
        working-directory: ./gh-pages
        run: |
          gap update.g

      - name: git -- commit the update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[${{ github.ref_name }}] - website update'
          repository: gh-pages
          branch: gh-pages
          push_options: '--force'
