---

name: release
run-name: release-${{ github.ref_name }}
on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  gap-branch: stable-4.14
  revision: ${{ github.event.repository.name }}-${{ github.ref_name }}
  archive-file:  ${{ github.event.repository.name }}-${{ github.ref_name }}.tar.gz

jobs:
  assets-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: git -- checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ env.gap-branch }}

      - name: gap -- build docs
        uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'

      - name: gap -- release package
        uses: gap-actions/release-pkg@main  # FIXME: switch to this to a tag

